// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuzikKatalogu.Data;

#nullable disable

namespace MuzikKatalogu.Migrations
{
    [DbContext(typeof(MuzikKataloguDbContext))]
    [Migration("20250612142225_AddNewDataAndImages")]
    partial class AddNewDataAndImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MuzikKatalogu.Models.Album", b =>
                {
                    b.Property<int>("AlbumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlbumId"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AlbumId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            AlbumId = 1,
                            ArtistId = 1,
                            CoverImageUrl = "/images/albums/queen_anightattheopera.jpg",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(1975, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Night at the Opera"
                        },
                        new
                        {
                            AlbumId = 2,
                            ArtistId = 1,
                            CoverImageUrl = "/images/albums/queen_newsoftheworld.jpg",
                            Price = 12.99m,
                            ReleaseDate = new DateTime(1977, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "News of the World"
                        },
                        new
                        {
                            AlbumId = 3,
                            ArtistId = 1,
                            CoverImageUrl = "/images/albums/queen_greatesthits.jpg",
                            Price = 15.99m,
                            ReleaseDate = new DateTime(1981, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Greatest Hits"
                        },
                        new
                        {
                            AlbumId = 25,
                            ArtistId = 1,
                            CoverImageUrl = "/images/albums/queen_thegame.jpg",
                            Price = 14.50m,
                            ReleaseDate = new DateTime(1980, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Game"
                        },
                        new
                        {
                            AlbumId = 4,
                            ArtistId = 2,
                            CoverImageUrl = "/images/albums/mj_thriller.jpg",
                            Price = 24.99m,
                            ReleaseDate = new DateTime(1982, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Thriller"
                        },
                        new
                        {
                            AlbumId = 26,
                            ArtistId = 2,
                            CoverImageUrl = "/images/albums/mj_bad.jpg",
                            Price = 20.00m,
                            ReleaseDate = new DateTime(1987, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bad"
                        },
                        new
                        {
                            AlbumId = 27,
                            ArtistId = 2,
                            CoverImageUrl = "/images/albums/mj_dangerous.jpg",
                            Price = 18.00m,
                            ReleaseDate = new DateTime(1991, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dangerous"
                        },
                        new
                        {
                            AlbumId = 5,
                            ArtistId = 3,
                            CoverImageUrl = "/images/albums/beatles_abbeyroad.jpg",
                            Price = 18.50m,
                            ReleaseDate = new DateTime(1969, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Abbey Road"
                        },
                        new
                        {
                            AlbumId = 6,
                            ArtistId = 3,
                            CoverImageUrl = "/images/albums/beatles_sgtpepper.jpg",
                            Price = 22.00m,
                            ReleaseDate = new DateTime(1967, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sgt. Pepper's Lonely Hearts Club Band"
                        },
                        new
                        {
                            AlbumId = 7,
                            ArtistId = 3,
                            CoverImageUrl = "/images/albums/beatles_revolver.jpg",
                            Price = 17.00m,
                            ReleaseDate = new DateTime(1966, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Revolver"
                        },
                        new
                        {
                            AlbumId = 28,
                            ArtistId = 3,
                            CoverImageUrl = "/images/albums/beatles_whitealbum.jpg",
                            Price = 25.00m,
                            ReleaseDate = new DateTime(1968, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The White Album"
                        },
                        new
                        {
                            AlbumId = 8,
                            ArtistId = 4,
                            CoverImageUrl = "/images/albums/madonna_likeavirgin.jpg",
                            Price = 14.00m,
                            ReleaseDate = new DateTime(1984, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Like a Virgin"
                        },
                        new
                        {
                            AlbumId = 9,
                            ArtistId = 4,
                            CoverImageUrl = "/images/albums/madonna_rayoflight.jpg",
                            Price = 16.00m,
                            ReleaseDate = new DateTime(1998, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ray of Light"
                        },
                        new
                        {
                            AlbumId = 10,
                            ArtistId = 5,
                            CoverImageUrl = "/images/albums/ledzeppelin_iv.jpg",
                            Price = 21.00m,
                            ReleaseDate = new DateTime(1971, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Led Zeppelin IV"
                        },
                        new
                        {
                            AlbumId = 11,
                            ArtistId = 5,
                            CoverImageUrl = "/images/albums/ledzeppelin_houses.jpg",
                            Price = 19.50m,
                            ReleaseDate = new DateTime(1973, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Houses of the Holy"
                        },
                        new
                        {
                            AlbumId = 29,
                            ArtistId = 5,
                            CoverImageUrl = "/images/albums/ledzeppelin_physicalgraffiti.jpg",
                            Price = 23.00m,
                            ReleaseDate = new DateTime(1975, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Physical Graffiti"
                        },
                        new
                        {
                            AlbumId = 12,
                            ArtistId = 6,
                            CoverImageUrl = "/images/albums/adele_21.jpg",
                            Price = 17.50m,
                            ReleaseDate = new DateTime(2011, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "21"
                        },
                        new
                        {
                            AlbumId = 13,
                            ArtistId = 6,
                            CoverImageUrl = "/images/albums/adele_25.jpg",
                            Price = 18.00m,
                            ReleaseDate = new DateTime(2015, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "25"
                        },
                        new
                        {
                            AlbumId = 14,
                            ArtistId = 7,
                            CoverImageUrl = "/images/albums/taylorswift_1989.jpg",
                            Price = 15.00m,
                            ReleaseDate = new DateTime(2014, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "1989"
                        },
                        new
                        {
                            AlbumId = 15,
                            ArtistId = 7,
                            CoverImageUrl = "/images/albums/taylorswift_red.jpg",
                            Price = 14.50m,
                            ReleaseDate = new DateTime(2012, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Red"
                        },
                        new
                        {
                            AlbumId = 30,
                            ArtistId = 7,
                            CoverImageUrl = "/images/albums/taylorswift_folklore.jpg",
                            Price = 16.00m,
                            ReleaseDate = new DateTime(2020, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Folklore"
                        },
                        new
                        {
                            AlbumId = 16,
                            ArtistId = 8,
                            CoverImageUrl = "/images/albums/eltonjohn_goodbyeyellowbrickroad.jpg",
                            Price = 16.50m,
                            ReleaseDate = new DateTime(1973, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Goodbye Yellow Brick Road"
                        },
                        new
                        {
                            AlbumId = 17,
                            ArtistId = 9,
                            CoverImageUrl = "/images/albums/pinkfloyd_darksideofthemoon.jpg",
                            Price = 25.00m,
                            ReleaseDate = new DateTime(1973, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Side of the Moon"
                        },
                        new
                        {
                            AlbumId = 18,
                            ArtistId = 9,
                            CoverImageUrl = "/images/albums/pinkfloyd_thewall.jpg",
                            Price = 23.00m,
                            ReleaseDate = new DateTime(1979, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Wall"
                        },
                        new
                        {
                            AlbumId = 19,
                            ArtistId = 10,
                            CoverImageUrl = "/images/albums/beyonce_lemonade.jpg",
                            Price = 17.00m,
                            ReleaseDate = new DateTime(2016, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lemonade"
                        },
                        new
                        {
                            AlbumId = 20,
                            ArtistId = 11,
                            CoverImageUrl = "/images/albums/eminem_mmlp.jpg",
                            Price = 15.50m,
                            ReleaseDate = new DateTime(2000, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Marshall Mathers LP"
                        },
                        new
                        {
                            AlbumId = 21,
                            ArtistId = 12,
                            CoverImageUrl = "/images/albums/rihanna_anti.jpg",
                            Price = 13.00m,
                            ReleaseDate = new DateTime(2016, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Anti"
                        },
                        new
                        {
                            AlbumId = 22,
                            ArtistId = 13,
                            CoverImageUrl = "/images/albums/coldplay_arushofblood.jpg",
                            Price = 14.00m,
                            ReleaseDate = new DateTime(2002, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Rush of Blood to the Head"
                        },
                        new
                        {
                            AlbumId = 23,
                            ArtistId = 14,
                            CoverImageUrl = "/images/albums/edsheeran_divide.jpg",
                            Price = 16.00m,
                            ReleaseDate = new DateTime(2017, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Divide"
                        },
                        new
                        {
                            AlbumId = 24,
                            ArtistId = 15,
                            CoverImageUrl = "/images/albums/maroon5_songsaboutjane.jpg",
                            Price = 12.00m,
                            ReleaseDate = new DateTime(2002, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Songs About Jane"
                        },
                        new
                        {
                            AlbumId = 31,
                            ArtistId = 6,
                            CoverImageUrl = "/images/albums/adele_21_deluxe.jpg",
                            Price = 19.00m,
                            ReleaseDate = new DateTime(2011, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "21 (Deluxe Edition)"
                        },
                        new
                        {
                            AlbumId = 32,
                            ArtistId = 17,
                            CoverImageUrl = "/images/albums/brunomars_doowops.jpg",
                            Price = 13.50m,
                            ReleaseDate = new DateTime(2010, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Doo-Wops & Hooligans"
                        },
                        new
                        {
                            AlbumId = 33,
                            ArtistId = 18,
                            CoverImageUrl = "/images/albums/arianagrande_sweetener.jpg",
                            Price = 15.00m,
                            ReleaseDate = new DateTime(2018, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sweetener"
                        },
                        new
                        {
                            AlbumId = 34,
                            ArtistId = 19,
                            CoverImageUrl = "/images/albums/billieeilish_whenweallfall.jpg",
                            Price = 16.50m,
                            ReleaseDate = new DateTime(2019, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "When We All Fall Asleep, Where Do We Go?"
                        },
                        new
                        {
                            AlbumId = 35,
                            ArtistId = 20,
                            CoverImageUrl = "/images/albums/dualipa_futurenostalgia.jpg",
                            Price = 14.00m,
                            ReleaseDate = new DateTime(2020, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Future Nostalgia"
                        },
                        new
                        {
                            AlbumId = 36,
                            ArtistId = 21,
                            CoverImageUrl = "/images/albums/harrystyles_fineline.jpg",
                            Price = 17.00m,
                            ReleaseDate = new DateTime(2019, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fine Line"
                        },
                        new
                        {
                            AlbumId = 37,
                            ArtistId = 22,
                            CoverImageUrl = "/images/albums/theweeknd_afterhours.jpg",
                            Price = 18.00m,
                            ReleaseDate = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "After Hours"
                        },
                        new
                        {
                            AlbumId = 38,
                            ArtistId = 23,
                            CoverImageUrl = "/images/albums/postmalone_hollywoodsbleeding.jpg",
                            Price = 15.50m,
                            ReleaseDate = new DateTime(2019, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hollywood's Bleeding"
                        },
                        new
                        {
                            AlbumId = 39,
                            ArtistId = 24,
                            CoverImageUrl = "/images/albums/justinbieber_purpose.jpg",
                            Price = 13.00m,
                            ReleaseDate = new DateTime(2015, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Purpose"
                        },
                        new
                        {
                            AlbumId = 40,
                            ArtistId = 25,
                            CoverImageUrl = "/images/albums/shakira_laundryservice.jpg",
                            Price = 11.00m,
                            ReleaseDate = new DateTime(2001, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Laundry Service"
                        },
                        new
                        {
                            AlbumId = 41,
                            ArtistId = 26,
                            CoverImageUrl = "/images/albums/rhcp_californication.jpg",
                            Price = 14.00m,
                            ReleaseDate = new DateTime(1999, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Californication"
                        },
                        new
                        {
                            AlbumId = 42,
                            ArtistId = 27,
                            CoverImageUrl = "/images/albums/foofighters_colourandshape.jpg",
                            Price = 12.00m,
                            ReleaseDate = new DateTime(1997, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Colour and the Shape"
                        },
                        new
                        {
                            AlbumId = 43,
                            ArtistId = 28,
                            CoverImageUrl = "/images/albums/acdc_backinblack.jpg",
                            Price = 19.00m,
                            ReleaseDate = new DateTime(1980, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Back in Black"
                        },
                        new
                        {
                            AlbumId = 44,
                            ArtistId = 29,
                            CoverImageUrl = "/images/albums/metallica_masterofpuppets.jpg",
                            Price = 17.00m,
                            ReleaseDate = new DateTime(1986, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Master of Puppets"
                        },
                        new
                        {
                            AlbumId = 45,
                            ArtistId = 30,
                            CoverImageUrl = "/images/albums/gunsnroses_appetite.jpg",
                            Price = 18.00m,
                            ReleaseDate = new DateTime(1987, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Appetite for Destruction"
                        });
                });

            modelBuilder.Entity("MuzikKatalogu.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"));

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            Bio = "İngiliz rock grubu. Eşsiz sahne performansları ve Freddie Mercury'nin karizmasıyla tanınırlar.",
                            ImageUrl = "/images/artists/queen.jpg",
                            Name = "Queen"
                        },
                        new
                        {
                            ArtistId = 2,
                            Bio = "Popun Kralı olarak bilinen Michael Jackson, müzik, dans ve moda dünyasında ikonik bir figürdür.",
                            ImageUrl = "/images/artists/michaeljackson.jpg",
                            Name = "Michael Jackson"
                        },
                        new
                        {
                            ArtistId = 3,
                            Bio = "Müzik tarihinin en etkili gruplarından biri olan The Beatles, 1960'larda rock müziği yeniden tanımladı.",
                            ImageUrl = "/images/artists/thebeatles.jpg",
                            Name = "The Beatles"
                        },
                        new
                        {
                            ArtistId = 4,
                            Bio = "Pop Kraliçesi Madonna, müzik ve moda dünyasındaki yenilikleriyle bilinir.",
                            ImageUrl = "/images/artists/madonna.jpg",
                            Name = "Madonna"
                        },
                        new
                        {
                            ArtistId = 5,
                            Bio = "Heavy metal ve hard rock'ın öncülerinden, blues-rock kökenli İngiliz grup.",
                            ImageUrl = "/images/artists/ledzeppelin.jpg",
                            Name = "Led Zeppelin"
                        },
                        new
                        {
                            ArtistId = 6,
                            Bio = "Güçlü sesi ve duygusal şarkı sözleriyle tanınan İngiliz şarkıcı-söz yazarı.",
                            ImageUrl = "/images/artists/adele.jpg",
                            Name = "Adele"
                        },
                        new
                        {
                            ArtistId = 7,
                            Bio = "Ülke ve pop müziği harmanlayan, etkileyici şarkı sözleriyle genç yaşta büyük başarılar elde eden sanatçı.",
                            ImageUrl = "/images/artists/taylorswift.jpg",
                            Name = "Taylor Swift"
                        },
                        new
                        {
                            ArtistId = 8,
                            Bio = "Dünyaca ünlü İngiliz piyanist, şarkıcı, söz yazarı ve besteci. Canlı performanslarıyla ünlüdür.",
                            ImageUrl = "/images/artists/eltonjohn.jpg",
                            Name = "Elton John"
                        },
                        new
                        {
                            ArtistId = 9,
                            Bio = "Progresif ve psikedelik rock'ın öncülerinden, felsefi şarkı sözleri ve deneysel müzikleriyle tanınır.",
                            ImageUrl = "/images/artists/pinkfloyd.jpg",
                            Name = "Pink Floyd"
                        },
                        new
                        {
                            ArtistId = 10,
                            Bio = "Küresel bir ikon, şarkıcı, söz yazarı, dansçı ve oyuncu. Sahne performansları ve güçlü vokalleriyle bilinir.",
                            ImageUrl = "/images/artists/beyonce.jpg",
                            Name = "Beyoncé"
                        },
                        new
                        {
                            ArtistId = 11,
                            Bio = "Tüm zamanların en çok satan rap sanatçılarından biri, karmaşık kafiyeleri ve kişisel hikayeleriyle ünlüdür.",
                            ImageUrl = "/images/artists/eminem.jpg",
                            Name = "Eminem"
                        },
                        new
                        {
                            ArtistId = 12,
                            Bio = "Barbadoslu şarkıcı, iş kadını ve oyuncu. Çeşitli müzik tarzlarını bir araya getiren hitleriyle tanınır.",
                            ImageUrl = "/images/artists/rihanna.jpg",
                            Name = "Rihanna"
                        },
                        new
                        {
                            ArtistId = 13,
                            Bio = "Duygusal rock marşları ve stadyum konserleriyle dünya çapında büyük bir hayran kitlesi olan İngiliz grup.",
                            ImageUrl = "/images/artists/coldplay.jpg",
                            Name = "Coldplay"
                        },
                        new
                        {
                            ArtistId = 14,
                            Bio = "Akustik gitarı ve samimi şarkı sözleriyle global başarı yakalayan İngiliz şarkıcı-söz yazarı.",
                            ImageUrl = "/images/artists/edsheeran.jpg",
                            Name = "Ed Sheeran"
                        },
                        new
                        {
                            ArtistId = 15,
                            Bio = "Funk, pop ve rock'ı harmanlayan, dünya çapında hit şarkılarıyla bilinen Amerikalı grup.",
                            ImageUrl = "/images/artists/maroon5.jpg",
                            Name = "Maroon 5"
                        },
                        new
                        {
                            ArtistId = 16,
                            Bio = "Benzersiz sesi ve duygusal şarkılarıyla tanınan İngiliz şarkıcı.",
                            ImageUrl = "/images/artists/adele.jpg",
                            Name = "Adele"
                        },
                        new
                        {
                            ArtistId = 17,
                            Bio = "Soul, funk, pop ve R&B'yi bir araya getiren hitleriyle ünlü Amerikalı şarkıcı, söz yazarı ve yapımcı.",
                            ImageUrl = "/images/artists/brunomars.jpg",
                            Name = "Bruno Mars"
                        },
                        new
                        {
                            ArtistId = 18,
                            Bio = "Geniş vokal aralığı ve pop ile R&B hitleriyle tanınan Amerikalı şarkıcı ve oyuncu.",
                            ImageUrl = "/images/artists/arianagrande.jpg",
                            Name = "Ariana Grande"
                        },
                        new
                        {
                            ArtistId = 19,
                            Bio = "Karanlık, atmosferik pop tarzıyla ve sıradışı vokal tekniğiyle öne çıkan genç Amerikalı şarkıcı.",
                            ImageUrl = "/images/artists/billieeilish.jpg",
                            Name = "Billie Eilish"
                        },
                        new
                        {
                            ArtistId = 20,
                            Bio = "Dans-pop ve pop türündeki şarkılarıyla tanınan İngiliz şarkıcı.",
                            ImageUrl = "/images/artists/dualipa.jpg",
                            Name = "Dua Lipa"
                        },
                        new
                        {
                            ArtistId = 21,
                            Bio = "One Direction grubunun eski üyesi, modern pop ve rock müziğiyle solo kariyerinde büyük başarı elde etti.",
                            ImageUrl = "/images/artists/harrystyles.jpg",
                            Name = "Harry Styles"
                        },
                        new
                        {
                            ArtistId = 22,
                            Bio = "R&B, pop ve soul'u harmanlayan, benzersiz vokalleri ve karanlık temalarıyla bilinen Kanadalı şarkıcı.",
                            ImageUrl = "/images/artists/theweeknd.jpg",
                            Name = "The Weeknd"
                        },
                        new
                        {
                            ArtistId = 23,
                            Bio = "Hip-hop, pop ve rock türlerini karıştıran Amerikalı şarkıcı, rapçi ve söz yazarı.",
                            ImageUrl = "/images/artists/postmalone.jpg",
                            Name = "Post Malone"
                        },
                        new
                        {
                            ArtistId = 24,
                            Bio = "Genç yaşta küresel bir fenomen haline gelen Kanadalı pop şarkıcısı.",
                            ImageUrl = "/images/artists/justinbieber.jpg",
                            Name = "Justin Bieber"
                        },
                        new
                        {
                            ArtistId = 25,
                            Bio = "Latin pop ve rock'ı harmanlayan, danslarıyla ve güçlü vokalleriyle bilinen Kolombiyalı süperstar.",
                            ImageUrl = "/images/artists/shakira.jpg",
                            Name = "Shakira"
                        },
                        new
                        {
                            ArtistId = 26,
                            Bio = "Funk rock ve alternatif rock'ın öncülerinden Amerikalı grup.",
                            ImageUrl = "/images/artists/redhotchilipeppers.jpg",
                            Name = "Red Hot Chili Peppers"
                        },
                        new
                        {
                            ArtistId = 27,
                            Bio = "Nirvana'nın davulcusu Dave Grohl tarafından kurulan Amerikalı rock grubu.",
                            ImageUrl = "/images/artists/foofighters.jpg",
                            Name = "Foo Fighters"
                        },
                        new
                        {
                            ArtistId = 28,
                            Bio = "Hard rock ve blues rock'ın efsanevi Avustralyalı grubu, yüksek enerjili sahne performanslarıyla bilinir.",
                            ImageUrl = "/images/artists/acdc.jpg",
                            Name = "AC/DC"
                        },
                        new
                        {
                            ArtistId = 29,
                            Bio = "Thrash metal'in öncülerinden ve en büyük gruplarından biri olan Amerikalı heavy metal grubu.",
                            ImageUrl = "/images/artists/metallica.jpg",
                            Name = "Metallica"
                        },
                        new
                        {
                            ArtistId = 30,
                            Bio = "Hard rock'ın ikonik gruplarından, 'Welcome to the Jungle' ve 'Sweet Child o' Mine' gibi hitleriyle ünlüdür.",
                            ImageUrl = "/images/artists/gunsnroses.jpg",
                            Name = "Guns N' Roses"
                        });
                });

            modelBuilder.Entity("MuzikKatalogu.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SongId"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("AudioFileUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("SongId");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            SongId = 1,
                            AlbumId = 1,
                            DurationSeconds = 354,
                            Title = "Bohemian Rhapsody"
                        },
                        new
                        {
                            SongId = 2,
                            AlbumId = 1,
                            DurationSeconds = 180,
                            Title = "Killer Queen"
                        },
                        new
                        {
                            SongId = 3,
                            AlbumId = 1,
                            DurationSeconds = 217,
                            Title = "Love of My Life"
                        },
                        new
                        {
                            SongId = 4,
                            AlbumId = 2,
                            DurationSeconds = 122,
                            Title = "We Will Rock You"
                        },
                        new
                        {
                            SongId = 5,
                            AlbumId = 2,
                            DurationSeconds = 179,
                            Title = "We Are the Champions"
                        },
                        new
                        {
                            SongId = 6,
                            AlbumId = 3,
                            DurationSeconds = 210,
                            Title = "Don't Stop Me Now"
                        },
                        new
                        {
                            SongId = 7,
                            AlbumId = 25,
                            DurationSeconds = 215,
                            Title = "Another One Bites the Dust"
                        },
                        new
                        {
                            SongId = 8,
                            AlbumId = 4,
                            DurationSeconds = 294,
                            Title = "Billie Jean"
                        },
                        new
                        {
                            SongId = 9,
                            AlbumId = 4,
                            DurationSeconds = 258,
                            Title = "Beat It"
                        },
                        new
                        {
                            SongId = 10,
                            AlbumId = 4,
                            DurationSeconds = 357,
                            Title = "Thriller"
                        },
                        new
                        {
                            SongId = 11,
                            AlbumId = 26,
                            DurationSeconds = 247,
                            Title = "Bad"
                        },
                        new
                        {
                            SongId = 12,
                            AlbumId = 27,
                            DurationSeconds = 257,
                            Title = "Smooth Criminal"
                        },
                        new
                        {
                            SongId = 13,
                            AlbumId = 5,
                            DurationSeconds = 259,
                            Title = "Come Together"
                        },
                        new
                        {
                            SongId = 14,
                            AlbumId = 5,
                            DurationSeconds = 182,
                            Title = "Something"
                        },
                        new
                        {
                            SongId = 15,
                            AlbumId = 5,
                            DurationSeconds = 185,
                            Title = "Here Comes the Sun"
                        },
                        new
                        {
                            SongId = 16,
                            AlbumId = 6,
                            DurationSeconds = 337,
                            Title = "A Day in the Life"
                        },
                        new
                        {
                            SongId = 17,
                            AlbumId = 7,
                            DurationSeconds = 159,
                            Title = "Yellow Submarine"
                        },
                        new
                        {
                            SongId = 18,
                            AlbumId = 28,
                            DurationSeconds = 285,
                            Title = "While My Guitar Gently Weeps"
                        },
                        new
                        {
                            SongId = 19,
                            AlbumId = 8,
                            DurationSeconds = 218,
                            Title = "Like a Virgin"
                        },
                        new
                        {
                            SongId = 20,
                            AlbumId = 9,
                            DurationSeconds = 318,
                            Title = "Vogue"
                        },
                        new
                        {
                            SongId = 21,
                            AlbumId = 9,
                            DurationSeconds = 377,
                            Title = "Frozen"
                        },
                        new
                        {
                            SongId = 22,
                            AlbumId = 10,
                            DurationSeconds = 482,
                            Title = "Stairway to Heaven"
                        },
                        new
                        {
                            SongId = 23,
                            AlbumId = 10,
                            DurationSeconds = 310,
                            Title = "Whole Lotta Love"
                        },
                        new
                        {
                            SongId = 24,
                            AlbumId = 29,
                            DurationSeconds = 512,
                            Title = "Kashmir"
                        },
                        new
                        {
                            SongId = 25,
                            AlbumId = 12,
                            DurationSeconds = 228,
                            Title = "Rolling in the Deep"
                        },
                        new
                        {
                            SongId = 26,
                            AlbumId = 12,
                            DurationSeconds = 285,
                            Title = "Someone Like You"
                        },
                        new
                        {
                            SongId = 27,
                            AlbumId = 13,
                            DurationSeconds = 295,
                            Title = "Hello"
                        },
                        new
                        {
                            SongId = 28,
                            AlbumId = 14,
                            DurationSeconds = 219,
                            Title = "Shake It Off"
                        },
                        new
                        {
                            SongId = 29,
                            AlbumId = 14,
                            DurationSeconds = 221,
                            Title = "Blank Space"
                        },
                        new
                        {
                            SongId = 30,
                            AlbumId = 15,
                            DurationSeconds = 328,
                            Title = "All Too Well"
                        },
                        new
                        {
                            SongId = 31,
                            AlbumId = 30,
                            DurationSeconds = 255,
                            Title = "Cardigan"
                        },
                        new
                        {
                            SongId = 32,
                            AlbumId = 16,
                            DurationSeconds = 340,
                            Title = "Tiny Dancer"
                        },
                        new
                        {
                            SongId = 33,
                            AlbumId = 17,
                            DurationSeconds = 398,
                            Title = "Money"
                        },
                        new
                        {
                            SongId = 34,
                            AlbumId = 18,
                            DurationSeconds = 383,
                            Title = "Comfortably Numb"
                        },
                        new
                        {
                            SongId = 35,
                            AlbumId = 19,
                            DurationSeconds = 206,
                            Title = "Formation"
                        },
                        new
                        {
                            SongId = 36,
                            AlbumId = 20,
                            DurationSeconds = 444,
                            Title = "Stan"
                        },
                        new
                        {
                            SongId = 37,
                            AlbumId = 21,
                            DurationSeconds = 219,
                            Title = "Work"
                        },
                        new
                        {
                            SongId = 38,
                            AlbumId = 22,
                            DurationSeconds = 307,
                            Title = "Clocks"
                        },
                        new
                        {
                            SongId = 39,
                            AlbumId = 23,
                            DurationSeconds = 233,
                            Title = "Shape of You"
                        },
                        new
                        {
                            SongId = 40,
                            AlbumId = 24,
                            DurationSeconds = 206,
                            Title = "This Love"
                        },
                        new
                        {
                            SongId = 41,
                            AlbumId = 32,
                            DurationSeconds = 233,
                            Title = "Locked Out of Heaven"
                        },
                        new
                        {
                            SongId = 42,
                            AlbumId = 33,
                            DurationSeconds = 227,
                            Title = "thank u, next"
                        },
                        new
                        {
                            SongId = 43,
                            AlbumId = 34,
                            DurationSeconds = 194,
                            Title = "Bad Guy"
                        },
                        new
                        {
                            SongId = 44,
                            AlbumId = 35,
                            DurationSeconds = 183,
                            Title = "Don't Start Now"
                        },
                        new
                        {
                            SongId = 45,
                            AlbumId = 36,
                            DurationSeconds = 174,
                            Title = "Watermelon Sugar"
                        },
                        new
                        {
                            SongId = 46,
                            AlbumId = 37,
                            DurationSeconds = 200,
                            Title = "Blinding Lights"
                        },
                        new
                        {
                            SongId = 47,
                            AlbumId = 38,
                            DurationSeconds = 207,
                            Title = "Circles"
                        },
                        new
                        {
                            SongId = 48,
                            AlbumId = 39,
                            DurationSeconds = 208,
                            Title = "What Do You Mean?"
                        },
                        new
                        {
                            SongId = 49,
                            AlbumId = 40,
                            DurationSeconds = 196,
                            Title = "Whenever, Wherever"
                        },
                        new
                        {
                            SongId = 50,
                            AlbumId = 41,
                            DurationSeconds = 266,
                            Title = "Under the Bridge"
                        });
                });

            modelBuilder.Entity("MuzikKatalogu.Models.Album", b =>
                {
                    b.HasOne("MuzikKatalogu.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MuzikKatalogu.Models.Song", b =>
                {
                    b.HasOne("MuzikKatalogu.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("MuzikKatalogu.Models.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("MuzikKatalogu.Models.Artist", b =>
                {
                    b.Navigation("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
